"""empty message

Revision ID: 65cb0949955c
Revises: 99f88c77882f
Create Date: 2022-03-28 23:35:59.755327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cb0949955c'
down_revision = '99f88c77882f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('details', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'details')
    # ### end Alembic commands ###
