"""empty message

Revision ID: 99f88c77882f
Revises: ad458b8918c5
Create Date: 2022-03-28 23:03:09.166109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f88c77882f'
down_revision = 'ad458b8918c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_user_updated_fkey', 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_updated', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('todos_user_updated_fkey', 'todos', 'user', ['user_updated'], ['id'])
    # ### end Alembic commands ###
