"""empty message

Revision ID: ad458b8918c5
Revises: 
Create Date: 2022-03-28 23:00:00.157849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad458b8918c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('usertype', sa.Enum('developer', 'designer', 'manager', name='UserTypes'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todos', sa.String(length=120), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('todo_type', sa.Enum('bug/issue', 'feature', 'improvements', name='TodoTypes'), nullable=False),
    sa.Column('stage', sa.Enum('notdone', 'inprogress', 'done', name='Stage'), nullable=False),
    sa.Column('acceptance', sa.Enum('approved', 'rejected', 'furtherreview', name='Acceptance'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_updated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_updated'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.drop_table('user')
    # ### end Alembic commands ###
